blank_issues_enabled: false
contact_links:
  - name: â“/ğŸš€/ğŸ’¬ Ask a Question / Feature Request / General Chat
    url: https://github.com/jovibor/HexCtrl/discussions/new
    about: Everything but bug-reports please post here.